#!/usr/bin/python
import sys
import os
import buildutils

Import ('user_options_dict')
Import ('library_env')
Import ('env')

bootloader_env = library_env.Copy ()

# Get all files from directory while applying ignore filter
source_dir   = Dir('#').abspath + os.sep + '/src/bootloader'
source_files = buildutils.listtrav(source_dir, source_dir)
source_files = buildutils.regexpfilter(source_files, user_options_dict['SOURCE_FILTER'], True)
source_files = buildutils.regexpfilter(source_files, user_options_dict['IGNORE_FILTER'], False)

source_files += ['../base/string.cxx', '../base/OS.cxx']

# ACE
bootloader_env.Append (CPPPATH = user_options_dict['ACE_INCLUDE'])
bootloader_env.Append (LIBPATH = user_options_dict['ACE_LIBPATH'])
bootloader_env.Append (LIBS    = user_options_dict['ACE_LIBRARY'])

bootloader = bootloader_env.Program (target='#'+user_options_dict['BUILD_DIR']+'/bin/stb-4.0', source=source_files)
env.Alias(target = ['install'], source = bootloader_env.Install(user_options_dict['INSTALL_ROOT_DIR'] + os.sep + user_options_dict['PREFIX']+'/bin', bootloader))
